[package]
name = "little_schemer"
version = "0.1.0"
authors = ["Richard Shepherd <richard@shepherd.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "2.0.2"
